apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-demo
  template:
    metadata:
      labels:
        app: react-demo
    spec:
      containers:
        - name: react-demo
          image: react-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
